import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        {/* desktop menu/header */}
        <header className="p-4">
          <div className="shadow-md justify-between hidden md:flex">
            {/* Left side of header */}
            <div>
              <Link href={"/"}>
              </Link>
            </div>

            {/* Right Side */}
            {/* Todo: hide admin page if not admin */}
            <div className="grid grid-cols-3 content-center gap-4">
              <Link
                href={"/admin"}
                className="font-bold text-2xl hover:underline"
              >
                Admin
              </Link>
              <Link
                href={"/books"}
                className="font-bold text-2xl hover:underline"
              >
                Boeken
              </Link>
              {/*Todo: Make profile page text "login" if nog logged it. Still redirect to profile though */}
              <Link
                href={"/profile"}
                className="font-bold text-2xl hover:underline"
              >
                Profile
              </Link>
            </div>
          </div>
        </header>

        {/*Main content*/}
        {children}

        {/* Mobile Menu */}
        <div className="fixed bottom-0 left-0 right-0 inset-shadow-2xs pt-3 rounded-xl h-[7vh] grid grid-cols-4 content-center gap-4 md:hidden items-stretch place-items-center">
          {/* Home page */}
          <Link href={"/"}>
            
          </Link>

          {/* Books page */}
          <Link href={"/books"}>
            
          </Link>

          {/* Profile page*/}

          <Link href={"/profile"}>
            
          </Link>

          {/* Admin page*/}
          {/* Todo: Hide if not admin or teacher */}
          <Link href={"/admin"}>
            
          </Link>
        </div>
      </body>
    </html>
  );
}
